### ISSUE TITLE
Adding JAV Scraper - www.javlibrary.com

### ISSUE THREAD

**Issue by Zero177768** [adultmm/AdultMediaManager#102]
The current JAV Scraper is not finding JAV Videos using the Video Code.
Example - spsa-097 , htb-003 , rctd-561
These 3 are able to be found on javlibrary.com
These were in with the first 10 I tried to scrape in my JAV folder.
The end result was 2 videos out of the 10 were found with the current scraper.
If you could add that site as a scarper that would be amazing :)
Thank you for all your work.

**Comment by adultmm** [comment]
As I can see, after a quick check, it'll be possible.

**Comment by Zero177768** [comment]
You Rock!!
 Thank you :)

**Comment by adultmm** [comment]
It's available in [v0.12.7](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.7).

**Comment by Zero177768** [comment]
Got a PayPal I can donate too

Sent via the Samsung Galaxy Z Fold5, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adultmm** [comment]
@Zero177768 Thank you, [You can donate here.](https://www.paypal.com/donate/?hosted_button_id=8AN7JHZZWTFQA)
