### ISSUE TITLE
iadf error image scraping?

### ISSUE THREAD

**Issue by wkearney99** [adultmm/AdultMediaManager#104]
It's not consistently repeatable, but a Rescrape Selected->Ask->All using just IAFD sometimes fails with the error:

Scraper: Internet Adult Film Database Message: Unsupported page: Cannot convert IAFD id to the new format. Id=we+%3c3+small+packages/2007,"EXCEPTION OCCURRED:AdultScraper.Shared.MovieScraper+UnsupportedPageException: Unsupported page: Cannot convert IAFD id to the new format. Id=we+%3c3+small+packages/2007

_And nothing in the source item uses the 'Id' text referenced above.  I'm guessing that's something the in source HTML on iafd being scraped._

That is I can scrape for a movie and it'll fail, but then succeed when tried again later.  So no reliable example to use for debugging.

Also, the logic on the dialog about not showing errors again doesn't seem to work?

**Comment by adultmm** [comment]
Finally I was able to replicate it. I refactored the ID conversion method, so I hope it'll fix the issue. These changes will be available in the next release. The error dialog logic will also be corrected. Thanks!

**Comment by adultmm** [comment]
Both issues have been fixed in [v0.12.11](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.11).
