### ISSUE TITLE
How to deal with tor.exe

### ISSUE THREAD

**Issue by Naozheng** [adultmm/AdultMediaManager#105]
I scrape using ember boundled installed version with Astrill as proxy app .

The main window just keeps running and there is no results or error prompt. 
![image](https://github.com/adultmm/AdultMediaManager/assets/102581434/e8438276-a50b-4c94-b13c-cc858ea0cb26)

There is a task named tor.exe appears under the ember manager
![image](https://github.com/adultmm/AdultMediaManager/assets/102581434/760f003b-967a-4a3b-aa76-fc7fe11695dd)

I tried to rename the zip file of tor.zip in the directory of  C:\Tools\AdultMediaManager\Modules\scraper.data.adult\3rdparty
then I can continue scraping. Howerver, I have to switch proxy severs every 2~3 successful scrapes. Sometimes there are error prompts of missing "tor.zip", but I can still continue after switch to another sever - a not-used-before sever.

It's exhausting when there are hundreds of videos to be scraped.

Would you please let me know how to deal with tor.exe?

**Comment by adultmm** [comment]
The AMM uses Tor to change its IP address when attempting to access a blocked website. I think its not compatible with your proxy app.
