### ISSUE TITLE
api.metadataapi.net not reachable error while scraping - Error 530

### ISSUE THREAD

**Issue by Cosmo-gh** [adultmm/AdultMediaManager#106]
nslookup api.metadataapi.net
Server:  xxx.home.xxx.com
Address:  172.16.100.1

***** xxx.home.xxx.com **can't find api.metadataapi.net: Non-existent domain**PS** 

nslookup metadataapi.net
Server:  xxx.home.xxx.com
Address:  172.16.100.1

Non-authoritative answer:
Name:    metadataapi.net
Addresses:  2606:4700:20::ac43:47ca
          2606:4700:20::681a:874
          2606:4700:20::681a:974
          104.26.9.116
          104.26.8.116
          172.67.71.202

**Comment by Cosmo-gh** [comment]
![image](https://github.com/adultmm/AdultMediaManager/assets/121356075/14ffb74c-3b15-45ea-93bb-2181d43a53cd)

**Comment by josephrohrer** [comment]
![Screenshot 2024-03-04 at 9 57 50 AM](https://github.com/adultmm/AdultMediaManager/assets/24574413/f7ff50b8-957c-4cc2-ad75-16550b5e4232)

**Comment by Cosmo-gh** [comment]
Sorry to hear that. Thank you for the great service!

**Comment by adultmm** [comment]
Yes-yes, sadly ThePornDB site is closed. I have to remove it from my plugin and try to handle its absence.

**Comment by adultmm** [comment]
@Cosmo-gh @josephrohrer v0.12.8 supports ThePornDB via the new URL.
