### ISSUE TITLE
Scraper: GayEroticVideoIndex.com can't work.

### ISSUE THREAD

**Issue by ghost** [adultmm/AdultMediaManager#107]
##Scraper: GayEroticVideoIndex.com can't work.

An error occurred during downloading the video information.  Scraper: GayEroticVideoIndex.com Message: One or more errors occurred. - One or more errors occurred.
Error log:
EXCEPTION OCCURRED:System.AggregateException: One or more errors occurred。 ---> System.AggregateException: One or more errors occurred. ---> PuppeteerSharp.NavigationException: net::ERR_CONNECTION_CLOSED at https://gayeroticvideoindex.com/video/4 at https://gayeroticvideoindex.com/video/4 ---> PuppeteerSharp.NavigationException: net::ERR_CONNECTION_CLOSED at https://gayeroticvideoindex.com/video/4
   In PuppeteerSharp.FrameManager.<NavigateAsync>d__43.MoveNext()
--- The end of the stack trace from the previous location where the exception was thrown ---
   In System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   In PuppeteerSharp.FrameManager.<NavigateFrameAsync>d__42.MoveNext()
--- End of inner exception stack trace ---
   In PuppeteerSharp.FrameManager.<NavigateFrameAsync>d__42.MoveNext()
--- The end of the stack trace from the previous location where the exception was thrown ---
   In System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   In AdultScraper.Shared.PuppeteerUtils.VB$StateMachine_14_DownloadPageContentBySelectorOrXPathAsync.MoveNext()
--- End of inner exception stack trace ---
   In System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   In AdultScraper.Shared.GayEroticVideoIndexMovieScraper._Closure$__10-0._Lambda$__0()
   In System.Threading.Tasks.Task`1.InnerInvoke()
   In System.Threading.Tasks.Task.Execute()
--- End of inner exception stack trace ---
   In System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   In AdultScraper.Shared.GayEroticVideoIndexMovieScraper.GetVideoByIdInternal(String externalId, String lang)
   In AdultScraper.Shared.VideoScraper.GetVideoById(String externalId, String lang)
---> (Internal exception #0) System.AggregateException: One or more errors occurred. ---> PuppeteerSharp.NavigationException: net::ERR_CONNECTION_CLOSED at https://gayeroticvideoindex.com/video/4 at https://gayeroticvideoindex.com/video/4 ---> PuppeteerSharp.NavigationException: net::ERR_CONNECTION_CLOSED at https://gayeroticvideoindex.com/video/4
   In PuppeteerSharp.FrameManager.<NavigateAsync>d__43.MoveNext()
--- The end of the stack trace from the previous location where the exception was thrown ---
   In System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   In PuppeteerSharp.FrameManager.<NavigateFrameAsync>d__42.MoveNext()
--- End of inner exception stack trace ---
   In PuppeteerSharp.FrameManager.<NavigateFrameAsync>d__42.MoveNext()
--- The end of the stack trace from the previous location where the exception was thrown ---
   In System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   In AdultScraper.Shared.PuppeteerUtils.VB$StateMachine_14_DownloadPageContentBySelectorOrXPathAsync.MoveNext()
--- End of inner exception stack trace ---
   In System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   In AdultScraper.Shared.GayEroticVideoIndexMovieScraper._Closure$__10-0._Lambda$__0()
   In System.Threading.Tasks.Task`1.InnerInvoke()
   In System.Threading.Tasks.Task.Execute()
---> (Internal exception #0) PuppeteerSharp.NavigationException: net::ERR_CONNECTION_CLOSED at https://gayeroticvideoindex.com/video/4 at https://gayeroticvideoindex.com/video/4 ---> PuppeteerSharp.NavigationException: net::ERR_CONNECTION_CLOSED at https://gayeroticvideoindex.com/video/4
   In PuppeteerSharp.FrameManager.<NavigateAsync>d__43.MoveNext()
--- The end of the stack trace from the previous location where the exception was thrown ---
   In System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   In PuppeteerSharp.FrameManager.<NavigateFrameAsync>d__42.MoveNext()
--- End of internal exception stack trace ---
   In PuppeteerSharp.FrameManager.<NavigateFrameAsync>d__42.MoveNext()
--- The end of the stack trace from the previous location where the exception was thrown ---
   In System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   In AdultScraper.Shared.PuppeteerUtils.VB$StateMachine_14_DownloadPageContentBySelectorOrXPathAsync.MoveNext()<---
<---
*   In System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   In AdultScraper.Shared.GayEroticVideoIndexMovieScraper.GetVideoByIdInternal(String externalId, String lang)
   In AdultScraper.Shared.VideoScraper.GetVideoById(String externalId, String lang)

**Comment by adultmm** [comment]
I've tested it with some movies and it works. Could you give me the movie you tried it with?
