### ISSUE TITLE
"Cannot found working Tor circuit"

### ISSUE THREAD

**Issue by GrafVonKrolock** [adultmm/AdultMediaManager#108]
I've been getting the following error message when trying to scrape.

![Snipaste_2024-04-05_15-23-44](https://github.com/adultmm/AdultMediaManager/assets/33816294/3f649edd-a486-44b1-9a85-70e806168067)

Since I don't use Tor nor DDG, I'm assuming this is an issue on the back-end of AMM, so I'm reporting it.

**Comment by adultmm** [comment]
AMM utilizes DuckDuckGo for searches on the IAFD if no results are found during the onsite search. Occasionally, DuckDuckGo blocks too many searches, so AMM attempts accessing DuckDuckGo via the Tor network. However, in your case, this was unsuccessful five times. I'll take a look at the DDG search.

**Comment by GrafVonKrolock** [comment]
Thanks.
I should add, though, that this is not exclusive to IAFD. It's happening on several scrapers - DATA18, GayEroticVideoIndex, IAFD - when scrapping video. They loop through each 2 times.
TPDB doesn't show the same error.

**Comment by adultmm** [comment]
Fixed in [v0.12.9](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.9).
