### ISSUE TITLE
JAV Database scraper also not working

### ISSUE THREAD

**Issue by Zero177768** [adultmm/AdultMediaManager#113]
JAV Database scraper not working:
See Images:

Manually searching website will give results on both
JAV Database
JAV Library
![Screenshot 2024-05-16 165017](https://github.com/adultmm/AdultMediaManager/assets/156572347/6f73f67a-930d-4e05-a1c5-90257adcca2c)
![Screenshot 2024-05-16 165127](https://github.com/adultmm/AdultMediaManager/assets/156572347/0c71c053-6a55-4944-9c0c-9798015ed35b)
![Screenshot 2024-05-16 165156](https://github.com/adultmm/AdultMediaManager/assets/156572347/2e66fc35-1aa0-4424-b3f9-06ebe75c51d3)

**Comment by Zero177768** [comment]
I think it is a CloudFlare issue

**Comment by adultmm** [comment]
Fixed in [v0.12.11](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.11).
