### ISSUE TITLE
JAV Scrapper Fix add in https://jav.guru/

### ISSUE THREAD

**Issue by Zero177768** [adultmm/AdultMediaManager#116]
Can you add this site as it does not look like it has CloudFlare when I download from there

Here is and example:   
 
https://jav.guru/375409/mudr-267-the-old-man-neighbor-and-a-bratty-girl-are-living-together-half-heartedly-hiding-from-their-parents-during-their-rebellious-period-yuyu-esumi/

Looks like it has the info need to fill in the metadata

**Comment by adultmm** [comment]
JAVDatabase is fixed in [v0.12.11](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.11). 
I'll check this site as well.

**Comment by adultmm** [comment]
Implemented in [v1.0.0-beta2](https://github.com/adultmm/AdultMediaManager/releases/tag/v1.0.0-beta2). 
There isn't runtime information and fewer images, but it works as far as I could test.
