### ISSUE TITLE
Kink scraper broken

### ISSUE THREAD

**Issue by chronotank79** [adultmm/AdultMediaManager#120]
Updated to 12.11, and Kink scraper gives this error:

Object reference not set to an instance of an object.

Tried rolling back to 12.10 and same error. other scrapers seem to be working okay still.

**Comment by adultmm** [comment]
Please, post the corresponding log file.

**Comment by chronotank79** [comment]
[2024-07-12.csv](https://github.com/user-attachments/files/16194389/2024-07-12.csv)

**Comment by adultmm** [comment]
Thanks, I'll fix it in the next version.

**Comment by adultmm** [comment]
Fixed in [v0.12.12](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.12)

**Comment by adultmm** [comment]
Try out the standalone version that works: [v1.0.0-beta1](https://github.com/adultmm/AdultMediaManager/releases/tag/v1.0.0-beta1).
