### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by CodyBerenson** [adultmm/AdultMediaManager#122]
Hello!  Thank you for what you do!  I have noticed that with each release, you list the Source Code as an asset, but the zips are empty.  Is that an oversight?  With your next release will you include your Source Code?  A donation would be forthcoming.  Thanks!

![image](https://github.com/user-attachments/assets/79a13d40-69da-4581-bd64-8e91f89a698c)

**Comment by adultmm** [comment]
Sorry, Cody, but I cannot publish the source code due copyright issues. I don't want any legal problems to me.
