### ISSUE TITLE
Adult DVD Empire no longer works

### ISSUE THREAD

**Issue by JerseyJoe856** [adultmm/AdultMediaManager#131]
I think it might be related to the new age verification question they intiated....but I cant get it to scrape at all.  Really appreciate the good work here....and would love to donate to help you going forward.

**Comment by wkearney99** [comment]
And what does the 'Manual ID' field want for that site?  It's not the full URL, or just the numeric part of the URL?

**Comment by JerseyJoe856** [comment]
I am not sure.  I am not a programmer.  I am just running the adult media manager.  AdultDVDempire is one of the main search tools, and probably the only one that pulls fanart for me.  When I run it now, I get a message "object reference not set to instance of object".  I know the website made a change recently to require age verification, so I am just guessing that is it.    I would assume many people are having the same issue, since AdultDVDempire is the main search tool.

**Comment by JerseyJoe856** [comment]
i think the way adultdvdempire works now is for the first time you enter their website with a new browser, its asks a one time question to click yes "enter" if youre over 18 (or no).  the next time you go to the website, it does not ask the question.

**Comment by adultmm** [comment]
Fixed in [v1.0.1](https://github.com/adultmm/AdultMediaManager/releases/tag/v1.0.1). @JerseyJoe856, any donation is very welcome.

**Comment by JerseyJoe856** [comment]
@adultmm thanks so much.  I just sent another donation.

**Comment by adultmm** [comment]
@JerseyJoe856, I truly appreciate your continued support. Thanks
