### ISSUE TITLE
make video scraper always search certain sites

### ISSUE THREAD

**Issue by primalxxx** [adultmm/AdultMediaManager#133]
so when i open a video and hit "change movie" to use the video scraper, i have to manually open the "select scraper" option to find some movies from say evil angel or bangbros.  can I make it always search these?  i only see options to make data18 and theporndb etc defaults.

**Comment by primalxxx** [comment]
![Screenshot_20241023_121901_Chrome](https://github.com/user-attachments/assets/775f8cab-ee25-4af9-a661-130d9bdaace3)
i saw someone else had the option in this area but i do not.  i am pretty sure im up to date on the app.

**Comment by wkearney99** [comment]
Did ya check the other tabs in that window?  Like the 'Movie scrapers' tab?  

Dig around, look at the various settings.  Might find something helpful?

**Comment by primalxxx** [comment]
The workaround I found was to rename the files to have the site name.  That way it always scrapes EvilAngel.com.
