### ISSUE TITLE
New Scraper

### ISSUE THREAD

**Issue by godfathertulpe** [adultmm/AdultMediaManager#16]
Hey!

I have a few more suggestions for possible new scrapers:

www vixen com
www x-art com
www hegre com
www frolicme com

Would be great if technically possible to be able to be involved.

Thanks for your great work!!!

**Comment by godfathertulpe** [comment]
Two more:

www xchimera com
www xconfessions com

;)

**Comment by adultmm** [comment]
All of the sites above are available in v0.10.0-BETA.1.
