### ISSUE TITLE
Legalporno

### ISSUE THREAD

**Issue by Nicho84** [adultmm/AdultMediaManager#20]
Hi,
I see that legalporno.net is being used as a scraper That site doesn't have all scenes.
You should change it to legalporno.com or analvids.com.

**Comment by adultmm** [comment]
Hi Nicho,

AnalVids.com scraper is also implemented since v0.8.0. 
What is your exact problem?

**Comment by Nicho84** [comment]
Ah, sorry, I see that now.
I had a Legalporno clip that were being scraped to Legalporno(.net) with no match, then when I *manually* changed to Analvids it was found hmm...

**Comment by adultmm** [comment]
The question is why weren't detected both scrapers. Could you give me the full path of the file?

**Comment by adultmm** [comment]
No answer, so I close it.
