### ISSUE TITLE
Adulttime.com scraper

### ISSUE THREAD

**Issue by chaitrakiran2010** [adultmm/AdultMediaManager#23]
Please add... 

Adult-Time-Originals
---
Adult-Time-Originals/Age-Beauty
Adult-Time-Originals/Asmr-Fantasy
Adult-Time-Originals/Be-The-Cuck
Adult-Time-Originals/Between-The-Sheets-Alison-Rey
Adult-Time-Originals/Bubblegum-Dungeon
Adult-Time-Originals/Cardiogasm
Adult-Time-Originals/Caught-Fapping
Adult-Time-Originals/Films
Adult-Time-Originals/Girlcore
Adult-Time-Originals/Girls-Under-Arrest
Adult-Time-Originals/Go-Stuck-Yourself
Adult-Time-Originals/Hentai-Sex-School
Adult-Time-Originals/How-Women-Orgasm
Adult-Time-Originals/Is-This-Real
Adult-Time-Originals/Joi-Mom
Adult-Time-Originals/Lady-Gonzo
Adult-Time-Originals/Model-Time
Adult-Time-Originals/Mommys-Boy
Adult-Time-Originals/Naked-Yoga-Life
Adult-Time-Originals/Pov-Massage
Adult-Time-Originals/Shape-Of-Beauty
Adult-Time-Originals/She-Wants-Him
Adult-Time-Originals/Shower-Solos
Adult-Time-Originals/Sistertrick
Adult-Time-Originals/Super-Horny-Fun-Time
Adult-Time-Originals/Transfixed
Adult-Time-Originals/Transgressive
Adult-Time-Originals/Unrelatedx
Adult-Time-Originals/We-Like-Girls

AlettaOceanLive
--

Bang-Originals
--
Bang-Originals/Castings
Bang-Originals/Confessions
Bang-Originals/Fck-News
Bang-Originals/Glamkore
Bang-Originals/Pretty-And-Raw
Bang-Originals/Rammed
Bang-Originals/Real-Milfs
Bang-Originals/Real-Teens
Bang-Originals/Roadside-Xxx
Bang-Originals/Screw-The-Cops
Bang-Originals/Surprise
Bang-Originals/Trickery
Bang-Originals/Yngr

Blowpass
--
Blowpass/1000-Facials
Blowpass/Mommy-Blows-Best
Blowpass/Only-Teen-Blowjobs
Blowpass/Throated

Cumlouder
--
Cumlouder/Bitch-Confessions
Cumlouder/Boldly-Girls
Cumlouder/Boobday
Cumlouder/Breaking-Asses
Cumlouder/Cocks-Xl
Cumlouder/Cum-Extreme
Cumlouder/Cum-Trick
Cumlouder/Ex-Girlfriends
Cumlouder/Fucking-Amateurs
Cumlouder/Fuckin-Van
Cumlouder/Give-Me-Spunk
Cumlouder/Handjob-Goddess
Cumlouder/Hungry-Cum-Eaters
Cumlouder/Latin-Asses-In-Public
Cumlouder/Living-With-A-Pornstar
Cumlouder/Living-With-Leyla
Cumlouder/Porn-Heros
Cumlouder/Pornstar-Fisher
Cumlouder/Pov
Cumlouder/Spoof-Porn
Cumlouder/Street-Suckers
Cumlouder/Stunning-Butts
Cumlouder/Sweet-18
Cumlouder/Tour

**Comment by adultmm** [comment]
Please, help me with one movie URL per site, e.g.:
Adult-Time-Originals/Girlcore: https://www.girlcore.com/en/video/Girlcore--S2-E2--WORKING-FOR-THE-WEEKEND/166276

I think if you can't find movie URLs, support for those sites is not possible. 

Thanks

**Comment by chaitrakiran2010** [comment]
What about adultprime.com

**Comment by adultmm** [comment]
I need test videos for all subsites because the structure of the subsites could be different. For example, I couldn't find video pages for Cardiogasm.com, but I found for Girlcore.com: https://www.girlcore.com/en/video/Girlcore--S2-E2--WORKING-FOR-THE-WEEKEND/166276 

So you - or anybody else - can support my work with finding video pages for all the sites you listed below: Age-Beauty, Asmr-Fantasy, ...

I hope I could clarify my request. :)

**Comment by chaitrakiran2010** [comment]
Some of them included in Girlsway.com

**Comment by chaitrakiran2010** [comment]
forget adulttimeoriginals.com and partner sites.

here is the original sites......

AlettaOceanLive.com
Bang.com
Blowpass.com
Cumlouder.com

**Comment by chaitrakiran2010** [comment]
Request list goes on...........
Allanal.com

https://tour.allanal.com/view/287/avery-gia-are-anal-fanatics
https://tour.trueanal.com/scenes/ailees-hot-anal-desires
https://tour.nympho.com/view/hooked-on-kylie
https://tour.analonly.com/view/95/marilyn-stretches-her-hole
https://tour.swallowed.com/view/885/filling-erin-bellas-throats

**Comment by adultmm** [comment]
Bang,com is now available in [v0.10.0-BETA.2](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.10.0-BETA.2)

**Comment by adultmm** [comment]
All of these sites are also available:
https://tour.allanal.com/view/287/avery-gia-are-anal-fanatics
https://tour.trueanal.com/scenes/ailees-hot-anal-desires
https://tour.nympho.com/view/hooked-on-kylie
https://tour.analonly.com/view/95/marilyn-stretches-her-hole
https://tour.swallowed.com/view/885/filling-erin-bellas-throats

**Comment by adultmm** [comment]
You're welcome. :) Please, create a new issue for every site or network. And [throw me a beer](https://www.paypal.com/donate/?hosted_button_id=8AN7JHZZWTFQA) if you can. Thanks
