### ISSUE TITLE
Scraper for alettaoceanlive.com 

### ISSUE THREAD

**Issue by chaitrakiran2010** [adultmm/AdultMediaManager#25]
if you can add scraper for alettaoceanlive.com
https://alettaoceanlive.com/tour/trailers/Happy-Valentines-Day.html

**Comment by adultmm** [comment]
Hi @chaitrakiran2010, 

There's no information on the pages (no description, no poster image, only the title), nor that you linked. What do you want to scrape?

**Comment by chaitrakiran2010** [comment]
Sorry… sorry …. It’s my fault
