### ISSUE TITLE
Scraper for blowpass.com

### ISSUE THREAD

**Issue by chaitrakiran2010** [adultmm/AdultMediaManager#26]
Please add…blowpass.com scraper
https://www.blowpass.com/en/video/throated/Gag-Her-With-A-Cock/199661
https://www.blowpass.com/en/video/mommyblowsbest/Stepmom-Needs-Relief-/199455
https://www.blowpass.com/en/video/onlyteenblowjobs/Sneaky-Sucker/199300
https://www.blowpass.com/en/video/1000facials/Good-Morning-From-Madi/192794
https://www.blowpass.com/en/video/immorallive/Hot-Redheads-Pussy-Stretched-by-Dinosaur-Cock-of-Porno-Dans-Stepson/197192

**Comment by adultmm** [comment]
added to my todo list

**Comment by adultmm** [comment]
Implemented in v0.10.1,

**Comment by chaitrakiran2010** [comment]
Thank you my friend... That means about 91% porn sites covered... (you already implemented ThePornDB, which covers 90% porn sites).
