### ISSUE TITLE
Scraper for zerotolerancefilms

### ISSUE THREAD

**Issue by chaitrakiran2010** [adultmm/AdultMediaManager#33]
Please add scraper for www.zerotolerancefilms.com

https://www.zerotolerancefilms.com/en/video/3rddegreefilms/MILF-Creampied-Stepmoms-5---Scene-4/194122
https://www.zerotolerancefilms.com/en/video/zerotolerancefilms/My-Roommates-A-Lesbian-3---Scene-3/174544

**Comment by adultmm** [comment]
It's available in [v0.11.1](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.1).
