### ISSUE TITLE
Scraper for plumperpass.com

### ISSUE THREAD

**Issue by chaitrakiran2010** [adultmm/AdultMediaManager#34]
Please add...Scraper for plumperpass.com

https://www.plumperpass.com/t1/showgal.php?g=content/PP/pp/4092pp/15218/60_1&s=584&uvar=MC4wLjAuMC4wLjAuMC4wLjA

**Comment by adultmm** [comment]
Released in [v0.11.2](https://github.com/adultmm/AdultMediaManager/releases/tag/).
