### ISSUE TITLE
Data18.com error

### ISSUE THREAD

**Issue by chaitrakiran2010** [adultmm/AdultMediaManager#35]
Data18.com gives Cannot set movie info : error.. for some files
and does not fetch images.

here is my issue: D (Drive), Brazzers(Folder), BabyGotBoobs - 18.10.29 - Tia Cyrus Mod Bod.mkv (File Name) 

scraper.Data.Adultscraper
Cannot set movie info : mod bot, tia cyrus - D:\Brazzers\BabyGotBoobs - 18.10.29 - Tia Cyrus Mod Bod.mkv

**Comment by adultmm** [comment]
Could you send the log file to me? (from the /Log/ folder) 

Thanks

**Comment by chaitrakiran2010** [comment]
Here is the log file
[2022-03-31.csv](https://github.com/adultmm/AdultMediaManager/files/8389251/2022-03-31.csv)

**Comment by chaitrakiran2010** [comment]
Yes my friend there is noting wrong in your plugin.. the https://imgbox.com/ not stable in my country. if I use VPN your plugin works perfectly.. Thank you once again.

**Comment by adultmm** [comment]
Thank you for your feedback! 
Anyway, I'll improve the error message in these cases.
