### ISSUE TITLE
Can you add these sites please?

### ISSUE THREAD

**Issue by DoucheHellSung** [adultmm/AdultMediaManager#37]
1. Brattymilf
2. Manyvids

**Comment by adultmm** [comment]
Brattymilf - this site is part of the NubilesNetwork, so I'll add it in the next version.
Manyvids - it has been requested a few times, it's a little bit bigger task, but I'll try to implement it as well.

**Comment by adultmm** [comment]
BrattyMILF scraper is now available in the [new alpha version](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.0-ALPHA.1)

**Comment by adultmm** [comment]
Both scrapers are available in [v0.11.0-BETA.1](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.0-BETA.1).
Enjoy, and open a new issue if you find any bugs. 

Cheers
