### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Topspliff** [adultmm/AdultMediaManager#44]
Hi, 

I have just found this link to this software and it looks great, however, when I try to install it I am getting a Trojan warning tr/crypt.cfi.gen

So of course am reluctant to install it on my system, can anyone confirm this is safe, if so why am I getting these warnings.

Cheers Alan

**Comment by paulie202** [comment]
Had the same issue. I'm getting multiple virus warnings.

**Comment by adultmm** [comment]
The exe file is only a self-extracting executable, so you can unzip it manually, and check the files with your antivirus software. I'm sure, the virus warning will be on one of the third-party libraries, not on my code.

With almost 4000 downloads, so I'm sure it's only a false positive virus warning.
 
[https://hanadigital.github.io/grev/?user=adultmm&repo=AdultMediaManager](https://hanadigital.github.io/grev/?user=adultmm&repo=AdultMediaManager)

**Comment by adultmm** [comment]
No answer, so I'm closing it.
