### ISSUE TITLE
HOW DO I SEE THE CODE?

### ISSUE THREAD

**Issue by paulie202** [adultmm/AdultMediaManager#47]
I'm on the releases page: https://github.com/adultmm/AdultMediaManager/releases

I'm clicking on Assets > Source code (zip). This downloads an empty zip folder.

When I downloaded the exe, I'm getting multiple virus warnings.

Can someone break down how to I would see the actual code in visual studio code?

**Comment by adultmm** [comment]
I cannot publish the source code because of copyright issues.

The exe file is only a self-extracting executable, so you can unzip it manually, and check the files with your antivirus software. I'm sure, the virus warning will be on one of the third-party libraries, not on my code.

**Comment by paulie202** [comment]
> I cannot publish the source code because of copyright issues.
> 
> The exe file is only a self-extracting executable, so you can unzip it manually, and check the files with your antivirus software. I'm sure, the virus warning will be on one of the third-party libraries, not on my code.

Thank you for the response. I'm confused about the copyright. Have you had issues in the past or is this a precaution? I have been using an evilangel scraper for a year without any issues. Link: https://gitlab.com/meanmrmustardgas/evilangel-dl

**Comment by adultmm** [comment]
Yes-yes, I got some emails in the past.

**Comment by paulie202** [comment]
> Yes-yes, I got some emails in the past.

Would you consider posting the code on somewhere like pastebin, maybe add a password for extra security or even burn after reading? Maybe use a vpn for further protection? I just want to see how you're doing this. It wouldn't take you more than a few minutes.

**Comment by paulie202** [comment]
> Yes-yes, I got some emails in the past.

Can you explain where the code is located within the exe file? I just want to know how you're grabbing the videos. Do you use selenium to click on the download links? Do you use requests? Do you use ffmpeg?

**Comment by adultmm** [comment]
Hi Paulie, 

I use the following tools:
- HtmlAgilityPack
- Tor Browser
- PuppeteerSharp with Chromium
- and some tricks to avoid site protections

I hope it helps you.
