### ISSUE TITLE
www.jeedoo.com

### ISSUE THREAD

**Issue by Deliverance28** [adultmm/AdultMediaManager#50]
Could this site be added to a movie scraper list? Seems to have a quite big database of different kind of movies.

https://www.jeedoo.com/porn-movies/

**Comment by adultmm** [comment]
Hi @Deliverance28,

I think it's possible, however, there is no plot nor tags, or categories for the movies. 

Could you send me some examples which are available on this site and AMM doesn't find them?

Thanks

**Comment by Deliverance28** [comment]
Well basically those current sites only list movies with english titles, so almost all german movies wont get scraped for example

**Comment by ghost** [comment]
How do you download AdultMediaManager plz

**Comment by adultmm** [comment]
Will be implemented in the next version.

**Comment by adultmm** [comment]
Released in [v0.11.5](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.5).
