### ISSUE TITLE
How to download 

### ISSUE THREAD

**Issue by ghost** [adultmm/AdultMediaManager#51]
It's this for Android or pc and how do you download it. My first time on GitHub

**Comment by adultmm** [comment]
It's for Windows PC only. 
There's the direct link for the installer:
https://github.com/adultmm/AdultMediaManager/releases/download/v0.11.1/AdultMediaManager.v0.11.1.x64.exe

**Comment by ghost** [comment]
Gutted looking for one for Android TV box
