### ISSUE TITLE
Ability to scrape videos as TV shows 

### ISSUE THREAD

**Issue by aSeaGhost** [adultmm/AdultMediaManager#52]
Hello 
I recently discovered AMM and this is a really awesome solution to replace my manual scraping scripts.
One thing I use to do is to register movies in the movie database, while sorting the videos in the TV shows section. Videos being grouped by site name as show name, and using years for seasons. 
Is there an option to use the AdultScraper in the TV show section ? or could it be something to plan ?

Thank you in advance

**Comment by adultmm** [comment]
It may be possible, however, there are some tricky questions - e.g. what should we do if there aren't date for the videos? 

Anyway, it's a quite big task, so I have no plan to implement it.
