### ISSUE TITLE
Can't import a movie in a folder with 'Sample' in the name?

### ISSUE THREAD

**Issue by wkearney99** [adultmm/AdultMediaManager#54]
Create a folder with 'Sample' as part of it's name.  Likewise a video in it.  Update Library will not import it.

Change the name of the folder/video and it works fine.

**Comment by adultmm** [comment]
This behavior is caused by Ember Media Manager, not my plugin. Please, report this issue to them. https://forum.kodi.tv/forumdisplay.php?fid=195
