### ISSUE TITLE
New Scraper - 1Pondo, Caribbeancom, Heyzo, 10Musume

### ISSUE THREAD

**Issue by Specialo** [adultmm/AdultMediaManager#55]
Hi,

What would the chances of a scraper for the below sites be ?

1Pondo, Caribbeancom, Heyzo, 10Musume

Thanks in advance.

**Comment by adultmm** [comment]
As I can see all of them could be possible. They had been added to my to-do list.

**Comment by adultmm** [comment]
All sites are implemented in v0.11.4, but the search on 1Pondo and 10Musume it's a joke, sometimes the exact match appears on the eighth result page. So the search could be really slow, more than a half minute.
