### ISSUE TITLE
New TS site request

### ISSUE THREAD

**Issue by MediaMetaDude** [adultmm/AdultMediaManager#56]
Hi

Thanks for the great program, it has helped me loads and only had one or two films it couldn't find info for.

Would it be possible to add pinkotgirls to the scrapers list?

Thanks

**Comment by adultmm** [comment]
Yes, it's possible. Added to my to-do list.

**Comment by adultmm** [comment]
Implemented in [v0.11.7](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.7).
