### ISSUE TITLE
New Scraper Request - straplez.com

### ISSUE THREAD

**Issue by MediaMetaDude** [adultmm/AdultMediaManager#57]
Found another site that AMM has issues with

straplez.com

Feel bad adding to your TODO list - if it is possible :D

**Comment by adultmm** [comment]
It's possible to scrape. Just my free time causes difficulty. :) We'll see,

**Comment by MediaMetaDude** [comment]
Well after I went to the site to manually put the movie info in, I found that somehow it had the wrong name, when I changed the file name to the right one, it found it without issue, I double checked the others and they worked as well.

So you can prob cross this off your list as user "error" ;)
