### ISSUE TITLE
Failed to access imgbox error

### ISSUE THREAD

**Issue by traiklin** [adultmm/AdultMediaManager#64]
I don't know why it keeps happening but when I scrape after more than like 5 files the program freezes up and then brings that error, I can access imgbox on my browser just fine but the app just freezes for like 3 minutes before bringing that error up and it doesn't do any images.

**Comment by adultmm** [comment]
This error means that my plugin cannot upload an image to ImgBox. Could you send the log file?

**Comment by traiklin** [comment]
[2022-11-05.csv](https://github.com/adultmm/AdultMediaManager/files/9959631/2022-11-05.csv)

Here is the last time it happened

**Comment by adultmm** [comment]
Unfortunately, it's a simple timeout when my plugin tries to upload an image to ImgBox. The timeout is 100 seconds, so it's more than enough. Some guys solved the problem by using a proxy. Maybe, we could integrate an other image store site, if you could suggest one. Requirements: unlimited image store time, and possibility to upload via API.
