### ISSUE TITLE
Request for Set/Collection option

### ISSUE THREAD

**Issue by MediaMetaDude** [adultmm/AdultMediaManager#65]
Would it be possible in a future release to add an option to put the set tag into the NFO when scraping

An example would be you make the set in movie sets, then when you scrape you can select a drop down menu and select which set from there

**Comment by adultmm** [comment]
EMM supports movie set handling. You can find it on the Set tab next to the Movies under the menubar, and "Add New MovieSet" point in the context menu.

**Comment by MediaMetaDude** [comment]
I know you can do that, what I was asking was for was an option to select the set(s) after you have made the from the edit movie page once you have scraped the movie, instead of having to go the sets tab
