### ISSUE TITLE
Max-Hardcore.com Scraper

### ISSUE THREAD

**Issue by bunfire** [adultmm/AdultMediaManager#7]
Fantastic work.. amazing. I've been curating my personal collection for the last couple of days and it's going perfect and my plex has never looked so fucking good.

Is adding a new scraper easy enough?  any chance to add http://max-hardcore.com

**Comment by bunfire** [comment]
@adultmm reopend.. opened it initially but then thought I should start a discussion.

**Comment by adultmm** [comment]
@bunfire The issue is perfect, everybody can see the progress. Thanks

Only small screenshot images are available to the videos on the site, but scraping is possible.

**Comment by adultmm** [comment]
It's available in v0.7.8.
