### ISSUE TITLE
javdatabase?

### ISSUE THREAD

**Issue by patcsong** [adultmm/AdultMediaManager#77]
Hello,

is it possible for you to add javdatabase?
collector normally save their file in movie code "ABC-0123"
of course if can search by name is also good

**Comment by adultmm** [comment]
Yes, it's possible, but only censored movies exist on the site. Uncensored movies link to JavHD, and the search doesn't work for them.

**Comment by patcsong** [comment]
yes, correct, in JAV. we mostly collect censored movie , because they have a better storyline :p
this website has a new good database.

I actually don't know how to use you plugin add on for my plex : (

**Comment by adultmm** [comment]
EmberMediaManager is a Windows application. Use it on a PC to scrape metadata for your collection. Unfortunately, Plex cannot read this metadata, so you have to install a plugin for your Plex: [https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle](https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle).

I hope this helps.

**Comment by patcsong** [comment]
Thank you very much. Now i understand how to use it already. will check how to make plex read the nfo file.

**Comment by adultmm** [comment]
JAV scraper is now available in [v0.12.0](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.0).
