### ISSUE TITLE
How to install and run AMM?

### ISSUE THREAD

**Issue by ranrinc** [adultmm/AdultMediaManager#78]
Very new and have not found any information on how to install and run it. Download both exe files and be able to run EMM but unsure what to do next. Help?

**Comment by adultmm** [comment]
Download AdultMediaManager.v0.11.7.x64.exe or the latest version. (NOT the plugin version!) It's a self-extractor executable, so choose a folder you want to install. In the new folder, start the Ember Media Manager.exe file. 

For more info visit Ember Media Manager website an forum.

**Comment by ranrinc** [comment]
Any chances that this will support sexart.com? I try but get nothing?

**Comment by adultmm** [comment]
This site is currently not [supported](https://github.com/adultmm/AdultMediaManager/wiki/Scraper-sources-%E2%80%A2-the-full-list). I have to write a scraper for it. Please create a new issue with this request, and I'll implement it.
