### ISSUE TITLE
Image scraper sources selectibility?

### ISSUE THREAD

**Issue by wkearney99** [adultmm/AdultMediaManager#79]
Movie scraping has the option to control which sites are used for data scraping.  But this does not exist for image scraping.

It would be helpful to be able to de-select sites in the same way for images.

Settings->Movies->Scrapers - Data->Movie Settings tab has checkboxes.
Settings->Movies->Scrapers - Images... does not have a settings tab like that.

The biggest reason being is some sites are causing AMM to hard-crash.  Most notably the Jeedo site.  If there's anything wrong during the scraping the error causes the app to quit.

**Comment by patcsong** [comment]
I agree in this, I untick the adult empire, becuase it was block in my country, but then it continue to search for image.

**Comment by adultmm** [comment]
I'm working on selecting the used scrapers for image scraping.
However, the Jeedo error is handled, so I'm afraid, some other error causes the app quit. Please, send me a log file with the error!

**Comment by adultmm** [comment]
This feature is available in [v0.12.0-BETA.2](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.0-BETA.2).
