### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by DrunkSith** [adultmm/AdultMediaManager#82]
When trying to scrape via the ThePornDB I get this error: 

---------------------------
Ember Media Manager
---------------------------
Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------

The app then closes and doesn't scrape the data. Seems to happen with a lot of files.

**Comment by adultmm** [comment]
I fixed some errors in [v0.12.0-BETA.3](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.0-BETA.3) and implemented the logging of unhandled exceptions. Please try to reproduce the error, and if it already exists, please send me the log file.

**Comment by DrunkSith** [comment]
Seems to be fixed thanks
