### ISSUE TITLE
DATA18.com error

### ISSUE THREAD

**Issue by SMWijthoef** [adultmm/AdultMediaManager#84]
while scraping a movie("A:\Porn\Everything Butt\EverythingButt.23.03.01.Summer.Col.and.Victoria.Voxxx.XXX.1080p.MP4-MiSTRESS[rarbg].mp4") i get the error "invalid DuckDuckGoJS repsons (1)."

error: ![Screenshot 2023-05-18 144527](https://github.com/adultmm/AdultMediaManager/assets/48009316/f27994bc-1916-47e7-ba2d-4eb71fc48918)
Log: [2023-05-18.csv](https://github.com/adultmm/AdultMediaManager/files/11507864/2023-05-18.csv)

**Comment by SMWijthoef** [comment]
also just got an error from kink.com

error: ![image](https://github.com/adultmm/AdultMediaManager/assets/48009316/1bc9157a-49a8-4094-8751-88487658fa61)
updated log: 
[2023-05-18.csv](https://github.com/adultmm/AdultMediaManager/files/11508993/2023-05-18.csv)

**Comment by adultmm** [comment]
Thanks for the detailed error report. Sometimes DuckDuckGo search engine drops an unwanted result. I've no idea why, but I'll try to solve it.

**Comment by adultmm** [comment]
Hi @SMWijthoef, I hope, I resolved this issue in [v0.12.2](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.2). Please, let me know is the problem still exists. Thanks
