### ISSUE TITLE
bangbros and familystrokes are not working

### ISSUE THREAD

**Issue by myxtrastufff** [adultmm/AdultMediaManager#87]
did a fresh install and bangbros and familystrokes are not working.

familystrokes the server returned an error 403 forbiden

bangbros nothing is ever found.

nubilefilms must have some kind of ddos system (I'm just guessing) because I think I scrapped too much from them and got my IP banned. Changed my IP and working again. Just scrapping that site much slower so I dont get banned again. Is there a way to do the automated scrape but slower? 

Other sites like Brazzers and Naughty America work fine.

**Comment by adultmm** [comment]
I'm working on a new version to fix the site structures that have changed. It'll arrive in a few days. 

What frequency do you think could be the default for scraping NublieFilms?

Thanks

**Comment by myxtrastufff** [comment]
I do not know what the frequency should be for Nublies. I have just been doing one every couple minutes for a hour a day. It's probably not an issue for someone that gets a new video every day or two but if you're trying to scrape a large collection it could be an issue.  I just tried Nublies from the "banned" IP an it worked today. So I guess they aren't doing a permanent ban but I wouldn't be surprised if they did if you keep scraping the site for a large collection. Would it be possible to create an adjustable timer or something that could be set by the user? Also, you can add NFBusty to your NubliesFilms scraper. I have found that it scrapes that site too.

Thanks again for all your hard work!

**Comment by adultmm** [comment]
Hi, I've fixed Bangbros in [v0.12.2](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.2), but FamilyStrokes works fine for me. If the problem still exists on your side, please send me the log file, and reopen this issue.

I also added NFBusty as a subsite of NublieFilms however, NFBusty.com is also available as a standalone scraper. 

I created a separeted issue (#88 ) for the request limiter for FamilyStrokes.

**Comment by myxtrastufff** [comment]
Can you explain how to get the log files from the scraper? I have tried to look through the settings and googled but I'm not finding anything. Sorry if this has been posted before and I missed it.

**Comment by adultmm** [comment]
There is a Log folder next to the "Ember Media Manager.exe" file. You can find the log files under it, e.g. 2023-07-11.csv.

**Comment by myxtrastufff** [comment]
got it and where do I send the file? Also upgraded to new ver BangBros works and FamilyStrokes does not. FamilyStrokes does work when using porndb but when I use porndb it only works for only a few scrapes then brings back nothing. So I try to use your scrapers for as many as possible.

**Comment by adultmm** [comment]
You can send the file here, just drag&drop the file to the comment box.

**Comment by myxtrastufff** [comment]
[2023-07-11.csv](https://github.com/adultmm/AdultMediaManager/files/12028258/2023-07-11.csv)

**Comment by adultmm** [comment]
Thanks. The scraper gets the forbidden error just as when trying to access the https://www.familystrokes.com/ page. Can you access this page from a browser? Is it possible that your IP is blocked?

**Comment by myxtrastufff** [comment]
yes, I have access to the site. Tried from a different location (IP and ISP inside the US) and get the same error. Site works in a browser at the different location.  I tried changing my DNS and get same error.

**Comment by adultmm** [comment]
I could reproduce this behaviour over the Tor network only with a compromitted IP address. Sorry, but I have no idea what could be wrong. Maybe you should use a VPN while scraping this site.
