### ISSUE TITLE
GEVI scraper won't download data or images

### ISSUE THREAD

**Issue by Goodlad84** [adultmm/AdultMediaManager#92]
Hey, am getting an error when using scraper for GayEroticVideoIndex. Other scrapers that I'm using seem to be working fine. 
The GEVI site seems revamped, and the basic search function seems to have more options (am not sure if this affects your scraper). I also recently had to reinstall Windows and recovered my AMM profile from a backup, so it's possible the issue is my end. 
I'm on v0.12.2. I was initially on EMM1.9.1. but I updated to 1.9.2 to see if this made any difference, it didn't. I recreated the error and attached the most recent log. Thanks

[2023-07-27.csv](https://github.com/adultmm/AdultMediaManager/files/12178873/2023-07-27.csv)

**Comment by adultmm** [comment]
Hi @Goodlad84, GEVI's site structure had changed, I'll update my plugin.

**Comment by adultmm** [comment]
Fixed in [v0.12.4](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.4).
