### ISSUE TITLE
IAFD scraper broken

### ISSUE THREAD

**Issue by DrunkSith** [adultmm/AdultMediaManager#93]
The IAFD scraper appears busted for me, I get the error:

---------------------------
Error
---------------------------
An error occurred during searching for the movie.

Scraper: Internet Adult Film Database
Message: id
---------------------------
OK   
---------------------------

**Comment by adultmm** [comment]
Hi @DrunkSith, 

IAFD uses a new ID format, so I have to update my scraper. It'll be available in the next release.

**Comment by adultmm** [comment]
Fixed in [v0.12.3](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.3)
