### ISSUE TITLE
Virus/Trojan

### ISSUE THREAD

**Issue by chest069** [adultmm/AdultMediaManager#98]
When I try and download the file I get that it was blocked due to a Virus/Trojan in the file. Is there another way to download the file? Thanks.

**Comment by adultmm** [comment]
The exe file is only a self-extracting executable, so you can unzip it manually and check the files with your antivirus software. I'm sure the virus warning will be on one of the third-party libraries, not in my code.

With more than 12000 downloads, I'm sure it's only a false positive virus warning.
https://hanadigital.github.io/grev/?user=adultmm&repo=AdultMediaManager
